# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 988)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(170, 30, 672, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.author = QtWidgets.QLabel(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(600, 90, 240, 27))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.author.setFont(font)
        self.author.setAlignment(QtCore.Qt.AlignCenter)
        self.author.setObjectName("author")
        self.mode = QtWidgets.QComboBox(self.centralwidget)
        self.mode.setGeometry(QtCore.QRect(50, 900, 171, 29))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.mode.setFont(font)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.modet = QtWidgets.QLabel(self.centralwidget)
        self.modet.setGeometry(QtCore.QRect(50, 870, 191, 27))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.modet.setFont(font)
        self.modet.setObjectName("modet")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(30, 150, 981, 711))
        self.display.setMinimumSize(QtCore.QSize(620, 620))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(48)
        self.display.setFont(font)
        self.display.setAlignment(QtCore.Qt.AlignCenter)
        self.display.setObjectName("display")
        self.selectt = QtWidgets.QLabel(self.centralwidget)
        self.selectt.setGeometry(QtCore.QRect(280, 860, 200, 50))
        self.selectt.setMinimumSize(QtCore.QSize(200, 50))
        self.selectt.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selectt.setFont(font)
        self.selectt.setObjectName("selectt")
        self.select = QtWidgets.QSpinBox(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(280, 900, 58, 29))
        self.select.setMinimumSize(QtCore.QSize(0, 20))
        self.select.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.select.setFont(font)
        self.select.setAlignment(QtCore.Qt.AlignCenter)
        self.select.setMinimum(1)
        self.select.setMaximum(28)
        self.select.setObjectName("select")
        self.loadt = QtWidgets.QLabel(self.centralwidget)
        self.loadt.setGeometry(QtCore.QRect(480, 860, 291, 50))
        self.loadt.setMinimumSize(QtCore.QSize(0, 50))
        self.loadt.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadt.setFont(font)
        self.loadt.setObjectName("loadt")
        self.load = QtWidgets.QLineEdit(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(460, 900, 261, 30))
        self.load.setMinimumSize(QtCore.QSize(0, 30))
        self.load.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.load.setFont(font)
        self.load.setObjectName("load")
        self.solve = QtWidgets.QPushButton(self.centralwidget)
        self.solve.setGeometry(QtCore.QRect(780, 860, 131, 60))
        self.solve.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.solve.setFont(font)
        self.solve.setObjectName("solve")
        self.result = QtWidgets.QPushButton(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(910, 860, 131, 60))
        self.result.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.author_2 = QtWidgets.QLabel(self.centralwidget)
        self.author_2.setGeometry(QtCore.QRect(700, 940, 381, 27))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.author_2.setFont(font)
        self.author_2.setAlignment(QtCore.Qt.AlignCenter)
        self.author_2.setObjectName("author_2")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(50, 90, 611, 50))
        self.info.setMinimumSize(QtCore.QSize(200, 50))
        self.info.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(800, 920, 99, 27))
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(930, 920, 99, 27))
        self.minus.setObjectName("minus")
        self.filee = QtWidgets.QPushButton(self.centralwidget)
        self.filee.setGeometry(QtCore.QRect(720, 900, 51, 27))
        self.filee.setObjectName("filee")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人工智能基础 大作业(Project for Artificial Intelligence Course)"))
        self.title.setText(_translate("MainWindow", "七巧板拼图（Tangram Solver）"))
        self.author.setText(_translate("MainWindow", "陈华玉 自76"))
        self.mode.setCurrentText(_translate("MainWindow", "7 pieces"))
        self.mode.setItemText(0, _translate("MainWindow", "7 pieces"))
        self.mode.setItemText(1, _translate("MainWindow", "9 pieces"))
        self.modet.setText(_translate("MainWindow", "模式(Game Mode):"))
        self.display.setText(_translate("MainWindow", "Display"))
        self.selectt.setText(_translate("MainWindow", "选择(Choose image):"))
        self.loadt.setText(_translate("MainWindow", "载入(load self-defined image):"))
        self.solve.setText(_translate("MainWindow", "演示(Solve)"))
        self.result.setText(_translate("MainWindow", "结果(Result)"))
        self.author_2.setText(_translate("MainWindow", "Chen Huayu     chendrag.github.io"))
        self.info.setText(_translate("MainWindow", "Welcome!"))
        self.plus.setText(_translate("MainWindow", ">"))
        self.minus.setText(_translate("MainWindow", "<"))
        self.filee.setText(_translate("MainWindow", "load"))
